// Secrets aren't declared in wrangler.jsonc (only `vars` are), so they don't
// appear in the `Env` interface generated by `wrangler types`. This merges
// them in. Regenerate worker-configuration.d.ts with `wrangler types`
// whenever `vars` in wrangler.jsonc changes; this file only needs updating
// when the set of secrets changes.
interface Env {
  TURNSTILE_SECRET_KEY: string;
  GITHUB_PAT: string;
}
